version: "3.8"
services:
  db:
    image: "postgres:13"
    ports: 
      - "5432:5432"
    volumes:
      - './schema.sql:/docker-entrypoint-initdb.d/schema.sql'
    environment:
      POSTGRES_USER: realworld
      POSTGRES_PASSWORD: realpassword